### ISSUE TITLE
This v9 version refers to a non-existent version of vardot_seo

### ISSUE THREAD

**Issue by HeneryH** [Vardot/varbase_blog#3]
Problem 1
    - drupal/varbase_blog 9.0.x-dev requires drupal/varbase_seo ^9 || 9.0.x-dev -> no matching package found.
    - vardot/varbase 9.0.x-dev requires drupal/varbase_blog 9.0.x-dev -> satisfiable by drupal/varbase_blog[9.0.x-dev].
    - Installation request for vardot/varbase 9.0.x-dev -> satisfiable by vardot/varbase[9.0.x-dev].

**Comment by Natshah** [comment]
Varbase 9.0.0-rc1 was released
Closing this issue
